name: Feature Request
description: 진행해야하는 신규 내용
title: "[Feature]: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        신규 프로젝트
  - type: input
    attributes:
      label: 내용
      placeholder: 내용을 입력해주세요.
  - type: textarea
    attributes:
      label: A
      description: A
      placeholder: AA
    validations:
      required: true
